export const GET_ANNOUNCEMENT = 'GET_ANNOUNCEMENT_REQUEST';
export const GET_ANNOUNCEMENT_SUCCESS = 'GET_ANNOUNCEMENT_SUCCESS';
export const GET_ANNOUNCEMENT_FAILURE = 'GET_ANNOUNCEMENT_FAILURE';

export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT_REQUEST';
export const ADD_ANNOUNCEMENT_SUCCESS = 'ADD_ANNOUNCEMENT_SUCCESS';
export const ADD_ANNOUNCEMENT_FAILURE = 'ADD_ANNOUNCEMENT_FAILURE';

export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT_REQUEST';
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS';
export const UPDATE_ANNOUNCEMENT_FAILURE = 'UPDATE_ANNOUNCEMENT_FAILURE';

export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT_REQUEST';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAILURE = 'DELETE_ANNOUNCEMENT_FAILURE';

export const PUBLISH_ANNOUNCEMENT = 'PUBLISH_ANNOUNCEMENT_REQUEST';
export const PUBLISH_ANNOUNCEMENT_SUCCESS = 'PUBLISH_ANNOUNCEMENT_SUCCESS';
export const PUBLISH_ANNOUNCEMENT_FAILURE = 'PUBLISH_ANNOUNCEMENT_FAILURE';

export const UNPUBLISH_ANNOUNCEMENT = 'UNPUBLISH_ANNOUNCEMENT_REQUEST';
export const UNPUBLISH_ANNOUNCEMENT_SUCCESS = 'UNPUBLISH_ANNOUNCEMENT_SUCCESS';
export const UNPUBLISH_ANNOUNCEMENT_FAILURE = 'UNPUBLISH_ANNOUNCEMENT_FAILURE';

