export const GET_TRAININGS = 'GET_TRAININGS_REQUEST';
export const GET_TRAININGS_SUCCESS = 'GET_TRAININGS_SUCCESS';
export const GET_TRAININGS_FAILURE = 'GET_TRAININGS_FAILURE';

export const GET_BY_ID_TRAINING = 'GET_BY_ID_TRAINING_REQUEST';
export const GET_BY_ID_TRAINING_SUCCESS = 'GET_BY_ID_TRAINING_SUCCESS';
export const GET_BY_ID_TRAINING_FAILURE = 'GET_BY_ID_TRAINING_FAILURE';

export const ADD_VIDEO_TRAINING = 'ADD_VIDEO_TRAINING_REQUEST';
export const ADD_VIDEO_TRAINING_SUCCESS = 'ADD_VIDEO_TRAINING_SUCCESS';
export const ADD_VIDEO_TRAINING_FAILURE = 'ADD_VIDEO_TRAINING_FAILURE';

export const EDIT_VIDEO_TRAINING = 'EDIT_VIDEO_TRAINING_REQUEST';
export const EDIT_VIDEO_TRAINING_SUCCESS = 'EDIT_VIDEO_TRAINING_SUCCESS';
export const EDIT_VIDEO_TRAINING_FAILURE = 'EDIT_VIDEO_TRAINING_FAILURE';

export const ADD_LIVE_TRAINING = 'ADD_LIVE_TRAINING_REQUEST';
export const ADD_LIVE_TRAINING_SUCCESS = 'ADD_LIVE_TRAINING_SUCCESS';
export const ADD_LIVE_TRAINING_FAILURE = 'ADD_LIVE_TRAINING_FAILURE';

export const EDIT_LIVE_TRAINING = 'EDIT_LIVE_TRAINING_REQUEST';
export const EDIT_LIVE_TRAINING_SUCCESS = 'EDIT_LIVE_TRAINING_SUCCESS';
export const EDIT_LIVE_TRAINING_FAILURE = 'EDIT_LIVE_TRAINING_FAILURE';

export const ADD_INTERACTIVE_TRAINING = 'ADD_INTERACTIVE_TRAINING_REQUEST';
export const ADD_INTERACTIVE_TRAINING_SUCCESS = 'ADD_INTERACTIVE_TRAINING_SUCCESS';
export const ADD_INTERACTIVE_TRAINING_FAILURE = 'ADD_INTERACTIVE_TRAINING_FAILURE';

export const EDIT_INTERACTIVE_TRAINING = 'EDIT_INTERACTIVE_TRAINING_REQUEST';
export const EDIT_INTERACTIVE_TRAINING_SUCCESS = 'EDIT_INTERACTIVE_TRAINING_SUCCESS';
export const EDIT_INTERACTIVE_TRAINING_FAILURE = 'EDIT_INTERACTIVE_TRAINING_FAILURE';

export const PUBLISH_TRAINING = 'PUBLISH_TRAINING_REQUEST';
export const PUBLISH_TRAINING_SUCCESS = 'PUBLISH_TRAINING_SUCCESS';
export const PUBLISH_TRAINING_FAILURE = 'PUBLISH_TRAINING_FAILURE';

export const UNPUBLISH_TRAINING = 'UNPUBLISH_TRAINING_REQUEST';
export const UNPUBLISH_TRAINING_SUCCESS = 'UNPUBLISH_TRAINING_SUCCESS';
export const UNPUBLISH_TRAINING_FAILURE = 'UNPUBLISH_TRAINING_FAILURE';

export const GET_QUESTIONS_BY_ID = 'GET_QUESTIONS_BY_ID_REQUEST';
export const GET_QUESTIONS_BY_ID_SUCCESS = 'GET_QUESTIONS_BY_ID_SUCCESS';
export const GET_QUESTIONS_BY_ID_FAILURE = 'GET_QUESTIONS_BY_ID_FAILURE';

export const GET_TRAINING_SLIDES_BY_ID = 'GET_TRAINING_SLIDES_BY_ID_REQUEST';
export const GET_TRAINING_SLIDES_BY_ID_SUCCESS = 'GET_TRAINING_SLIDES_BY_ID_SUCCESS';
export const GET_TRAINING_SLIDES_BY_ID_FAILURE = 'GET_TRAINING_SLIDES_BY_ID_FAILURE';
