//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACG.SGLN.Lottery.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACG.SGLN.Lottery.Domain.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        internal static string AdministrationType_Administration {
            get {
                return ResourceManager.GetString("AdministrationType_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commerciales.
        /// </summary>
        internal static string AdministrationType_Sales {
            get {
                return ResourceManager.GetString("AdministrationType_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Techniques.
        /// </summary>
        internal static string AdministrationType_Technical {
            get {
                return ResourceManager.GetString("AdministrationType_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel.
        /// </summary>
        internal static string DocumentFormat_Excel {
            get {
                return ResourceManager.GetString("DocumentFormat_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        internal static string DocumentFormat_None {
            get {
                return ResourceManager.GetString("DocumentFormat_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pdf.
        /// </summary>
        internal static string DocumentFormat_Pdf {
            get {
                return ResourceManager.GetString("DocumentFormat_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Généré automatiquement.
        /// </summary>
        internal static string DocumentSpec_AutoGenerated {
            get {
                return ResourceManager.GetString("DocumentSpec_AutoGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        internal static string DocumentSpec_None {
            get {
                return ResourceManager.GetString("DocumentSpec_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formalités administratives.
        /// </summary>
        internal static string DocumentSpec_PaperWork {
            get {
                return ResourceManager.GetString("DocumentSpec_PaperWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contenu de l&apos;annonce.
        /// </summary>
        internal static string DocumentType_AnnouncementContent {
            get {
                return ResourceManager.GetString("DocumentType_AnnouncementContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo de couverture d&apos;annonce.
        /// </summary>
        internal static string DocumentType_AnnouncementCoverPicture {
            get {
                return ResourceManager.GetString("DocumentType_AnnouncementCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Librairie médiatique.
        /// </summary>
        internal static string DocumentType_MediaLibraryDocument {
            get {
                return ResourceManager.GetString("DocumentType_MediaLibraryDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document officiel.
        /// </summary>
        internal static string DocumentType_OfficialDocument {
            get {
                return ResourceManager.GetString("DocumentType_OfficialDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ressource officielle.
        /// </summary>
        internal static string DocumentType_OfficialRessource {
            get {
                return ResourceManager.GetString("DocumentType_OfficialRessource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;un document audio.
        /// </summary>
        internal static string DocumentType_RequestAudioDocument {
            get {
                return ResourceManager.GetString("DocumentType_RequestAudioDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande photo de couverture de la catégorie.
        /// </summary>
        internal static string DocumentType_RequestCategoryCoverPicture {
            get {
                return ResourceManager.GetString("DocumentType_RequestCategoryCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;un document image.
        /// </summary>
        internal static string DocumentType_RequestImageDocument {
            get {
                return ResourceManager.GetString("DocumentType_RequestImageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande photo de couverture de la nature.
        /// </summary>
        internal static string DocumentType_RequestNatureCoverPicture {
            get {
                return ResourceManager.GetString("DocumentType_RequestNatureCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;un document PDF.
        /// </summary>
        internal static string DocumentType_RequestPdfDocument {
            get {
                return ResourceManager.GetString("DocumentType_RequestPdfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document de la boite à outils.
        /// </summary>
        internal static string DocumentType_ToolboxDocument {
            get {
                return ResourceManager.GetString("DocumentType_ToolboxDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certificat de formation.
        /// </summary>
        internal static string DocumentType_TrainingCertificate {
            get {
                return ResourceManager.GetString("DocumentType_TrainingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diapositive du cours de formation.
        /// </summary>
        internal static string DocumentType_TrainingCourseSlide {
            get {
                return ResourceManager.GetString("DocumentType_TrainingCourseSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo de couverture de formation.
        /// </summary>
        internal static string DocumentType_TrainingCoverPicture {
            get {
                return ResourceManager.GetString("DocumentType_TrainingCoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier de support de formation.
        /// </summary>
        internal static string DocumentType_TrainingSupportFile {
            get {
                return ResourceManager.GetString("DocumentType_TrainingSupportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payée.
        /// </summary>
        internal static string InvoiceStatusType_Paid {
            get {
                return ResourceManager.GetString("InvoiceStatusType_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impayée.
        /// </summary>
        internal static string InvoiceStatusType_Unpaid {
            get {
                return ResourceManager.GetString("InvoiceStatusType_Unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerte.
        /// </summary>
        internal static string NotificationType_Alert {
            get {
                return ResourceManager.GetString("NotificationType_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notification.
        /// </summary>
        internal static string NotificationType_Notification {
            get {
                return ResourceManager.GetString("NotificationType_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction Commerciale et Opérations.
        /// </summary>
        internal static string ProcessingDirectionType_DCO {
            get {
                return ResourceManager.GetString("ProcessingDirectionType_DCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction Contrôle Permanent et Risk Management.
        /// </summary>
        internal static string ProcessingDirectionType_DCPRM {
            get {
                return ResourceManager.GetString("ProcessingDirectionType_DCPRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction Finances et Support.
        /// </summary>
        internal static string ProcessingDirectionType_DFS {
            get {
                return ResourceManager.GetString("ProcessingDirectionType_DFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Direction Marketing et Développement.
        /// </summary>
        internal static string ProcessingDirectionType_DMD {
            get {
                return ResourceManager.GetString("ProcessingDirectionType_DMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agent externe.
        /// </summary>
        internal static string RequestAffectationType_ExternalAgent {
            get {
                return ResourceManager.GetString("RequestAffectationType_ExternalAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Agent interne.
        /// </summary>
        internal static string RequestAffectationType_InternalAgent {
            get {
                return ResourceManager.GetString("RequestAffectationType_InternalAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        internal static string RequestAffectationType_None {
            get {
                return ResourceManager.GetString("RequestAffectationType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changement équipement.
        /// </summary>
        internal static string RequestCategoryType_EquipementChanging {
            get {
                return ResourceManager.GetString("RequestCategoryType_EquipementChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réparer un équipement.
        /// </summary>
        internal static string RequestCategoryType_EquipementRepairing {
            get {
                return ResourceManager.GetString("RequestCategoryType_EquipementRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demander un équipement.
        /// </summary>
        internal static string RequestCategoryType_EquipementRequesting {
            get {
                return ResourceManager.GetString("RequestCategoryType_EquipementRequesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer vos données personnelles.
        /// </summary>
        internal static string RequestCategoryType_PersonalInformationChanging {
            get {
                return ResourceManager.GetString("RequestCategoryType_PersonalInformationChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour de l&apos;objectif mensuel.
        /// </summary>
        internal static string RequestCategoryType_UpdateMonthlyGoal {
            get {
                return ResourceManager.GetString("RequestCategoryType_UpdateMonthlyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour de l&apos;objectif hebdomadaire.
        /// </summary>
        internal static string RequestCategoryType_UpdateWeeklyGoal {
            get {
                return ResourceManager.GetString("RequestCategoryType_UpdateWeeklyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour de l&apos;objectif annuel.
        /// </summary>
        internal static string RequestCategoryType_UpdateYearlyGoal {
            get {
                return ResourceManager.GetString("RequestCategoryType_UpdateYearlyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrative et financière.
        /// </summary>
        internal static string RequestNatureType_Administration {
            get {
                return ResourceManager.GetString("RequestNatureType_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commerciales et Marketing.
        /// </summary>
        internal static string RequestNatureType_Sales {
            get {
                return ResourceManager.GetString("RequestNatureType_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Techniques et Opérations.
        /// </summary>
        internal static string RequestNatureType_Technical {
            get {
                return ResourceManager.GetString("RequestNatureType_Technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        internal static string RequestObjectType_Administration {
            get {
                return ResourceManager.GetString("RequestObjectType_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back-Office.
        /// </summary>
        internal static string RequestOrigin_BO {
            get {
                return ResourceManager.GetString("RequestOrigin_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Front-Office.
        /// </summary>
        internal static string RequestOrigin_FO {
            get {
                return ResourceManager.GetString("RequestOrigin_FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulée.
        /// </summary>
        internal static string RequestStatusType_Cancelled {
            get {
                return ResourceManager.GetString("RequestStatusType_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clôturée.
        /// </summary>
        internal static string RequestStatusType_Closed {
            get {
                return ResourceManager.GetString("RequestStatusType_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contestée.
        /// </summary>
        internal static string RequestStatusType_Contested {
            get {
                return ResourceManager.GetString("RequestStatusType_Contested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cours.
        /// </summary>
        internal static string RequestStatusType_InProgress {
            get {
                return ResourceManager.GetString("RequestStatusType_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyée.
        /// </summary>
        internal static string RequestStatusType_Submitted {
            get {
                return ResourceManager.GetString("RequestStatusType_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ascendant.
        /// </summary>
        internal static string SortDirection_Ascending {
            get {
                return ResourceManager.GetString("SortDirection_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descendant.
        /// </summary>
        internal static string SortDirection_Descending {
            get {
                return ResourceManager.GetString("SortDirection_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours terminé.
        /// </summary>
        internal static string TrainingStatusType_CourseFinished {
            get {
                return ResourceManager.GetString("TrainingStatusType_CourseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cours.
        /// </summary>
        internal static string TrainingStatusType_InProgress {
            get {
                return ResourceManager.GetString("TrainingStatusType_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test terminé.
        /// </summary>
        internal static string TrainingStatusType_TestCompleted {
            get {
                return ResourceManager.GetString("TrainingStatusType_TestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interactif.
        /// </summary>
        internal static string TrainingType_Interactive {
            get {
                return ResourceManager.GetString("TrainingType_Interactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En direct.
        /// </summary>
        internal static string TrainingType_Live {
            get {
                return ResourceManager.GetString("TrainingType_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vidéo.
        /// </summary>
        internal static string TrainingType_Video {
            get {
                return ResourceManager.GetString("TrainingType_Video", resourceCulture);
            }
        }
    }
}
