export const GET_USERS = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USER = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const GET_CONNECTED_USER = "GET_CONNECTED_USER_REQUEST";
export const GET_CONNECTED_USER_SUCCESS = "GET_CONNECTED_USER_SUCCESS";
export const GET_CONNECTED_USER_FAILURE = "GET_CONNECTED_USER_FAILURE";

export const DELETE_USER = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const CREATE_USER = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const ACTIVATE_USER = "ACTIVATE_USER_REQUEST";
export const ACTIVATE_USER_SUCCESS = "ACTIVATE_USER_SUCCESS";
export const ACTIVATE_USER_FAILURE = "ACTIVATE_USER_FAILURE";

export const INACTIVATE_USER = "INACTIVATE_USER_REQUEST";
export const INACTIVATE_USER_SUCCESS = "INACTIVATE_USER_SUCCESS";
export const INACTIVATE_USER_FAILURE = "INACTIVATE_USER_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const VALIDATE_RETAILER = "VALIDATE_RETAILER_REQUEST";
export const VALIDATE_RETAILER_SUCCESS = "VALIDATE_RETAILER_SUCCESS";
export const VALIDATE_RETAILER_FAILURE = "VALIDATE_RETAILER_FAILURE";

export const GET_USERS_ROLE_WISE = "GET_USERS_ROLE_WISE_REQUEST";
export const GET_USERS_ROLE_WISE_SUCCESS = "GET_USERS_ROLE_WISE_SUCCESS";
export const GET_USERS_ROLE_WISE_FAILURE = "GET_USERS_ROLE_WISE_FAILURE";