export const GET_APPLICATION_SETTING = 'GET_APPLICATION_SETTING_REQUEST';
export const GET_APPLICATION_SETTING_SUCCESS = 'GET_APPLICATION_SETTING_SUCCESS';
export const GET_APPLICATION_SETTING_FAILURE = 'GET_APPLICATION_SETTING_FAILURE';

export const ADD_APPLICATION_SETTING = 'ADD_APPLICATION_SETTING_REQUEST';
export const ADD_APPLICATION_SETTING_SUCCESS = 'ADD_APPLICATION_SETTING_SUCCESS';
export const ADD_APPLICATION_SETTING_FAILURE = 'ADD_APPLICATION_SETTING_FAILURE';

export const UPDATE_APPLICATION_SETTING = 'UPDATE_APPLICATION_SETTING_REQUEST';
export const UPDATE_APPLICATION_SETTING_SUCCESS = 'UPDATE_APPLICATION_SETTING_SUCCESS';
export const UPDATE_APPLICATION_SETTING_FAILURE = 'UPDATE_APPLICATION_SETTING_FAILURE';

export const DELETE_APPLICATION_SETTING = 'DELETE_APPLICATION_SETTING_REQUEST';
export const DELETE_APPLICATION_SETTING_SUCCESS = 'DELETE_APPLICATION_SETTING_SUCCESS';
export const DELETE_APPLICATION_SETTING_FAILURE = 'DELETE_APPLICATION_SETTING_FAILURE';

export const ACTIVATE_APPLICATION_SETTING = 'ACTIVATE_APPLICATION_SETTING_REQUEST';
export const ACTIVATE_APPLICATION_SETTING_SUCCESS = 'ACTIVATE_APPLICATION_SETTING_SUCCESS';
export const ACTIVATE_APPLICATION_SETTING_FAILURE = 'ACTIVATE_APPLICATION_SETTING_FAILURE';

export const INACTIVATE_APPLICATION_SETTING = 'INACTIVATE_APPLICATION_SETTING_REQUEST';
export const INACTIVATE_APPLICATION_SETTING_SUCCESS = 'INACTIVATE_APPLICATION_SETTING_SUCCESS';
export const INACTIVATE_APPLICATION_SETTING_FAILURE = 'INACTIVATE_APPLICATION_SETTING_FAILURE';