export const GET_REQUESTS = "GET_REQUESTS_REQUEST";
export const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";
export const GET_REQUESTS_FAILURE = "GET_REQUESTS_FAILURE";

export const GET_REQUESTS_BY_ID = "GET_REQUESTS_BY_ID_REQUEST";
export const GET_REQUESTS_BY_ID_SUCCESS = "GET_REQUESTS_BY_ID_SUCCESS";
export const GET_REQUESTS_BY_ID_FAILURE = "GET_REQUESTS_BY_ID_FAILURE";

export const START_REQUESTS = "START_REQUESTS_REQUEST";
export const START_REQUESTS_SUCCESS = "START_REQUESTS_SUCCESS";
export const START_REQUESTS_FAILURE = "START_REQUESTS_FAILURE";

export const CLOSE_REQUESTS = "CLOSE_REQUESTS_REQUEST";
export const CLOSE_REQUESTS_SUCCESS = "CLOSE_REQUESTS_SUCCESS";
export const CLOSE_REQUESTS_FAILURE = "CLOSE_REQUESTS_FAILURE";

export const ASSIGN_REQUESTS = "ASSIGN_REQUESTS_REQUEST";
export const ASSIGN_REQUESTS_SUCCESS = "ASSIGN_REQUESTS_SUCCESS";
export const ASSIGN_REQUESTS_FAILURE = "ASSIGN_REQUESTS_FAILURE";
