export const GET_REQUESTS_COMMENT = 'GET_REQUESTS_COMMENT_REQUEST';
export const GET_REQUESTS_COMMENT_SUCCESS = 'GET_REQUESTS_COMMENT_SUCCESS';
export const GET_REQUESTS_COMMENT_FAILURE = 'GET_REQUESTS_COMMENT_FAILURE';

export const GET_REQUESTS_COMMENT_BY_ID = 'GET_REQUESTS_COMMENT_BY_ID_REQUEST';
export const GET_REQUESTS_COMMENT_BY_ID_SUCCESS = 'GET_REQUESTS_COMMENT_BY_ID_SUCCESS';
export const GET_REQUESTS_COMMENT_BY_ID_FAILURE = 'GET_REQUESTS_COMMENT_BY_ID_FAILURE';

export const CREATE_REQUESTS_COMMENT = 'CREATE_REQUESTS_COMMENT_REQUEST';
export const CREATE_REQUESTS_COMMENT_SUCCESS = 'CREATE_REQUESTS_COMMENT_SUCCESS';
export const CREATE_REQUESTS_COMMENT_FAILURE = 'CREATE_REQUESTS_COMMENT_FAILURE';

export const DELETE_REQUESTS_COMMENT = 'DELETE_REQUESTS_COMMENT_REQUEST';
export const DELETE_REQUESTS_COMMENT_SUCCESS = 'DELETE_REQUESTS_COMMENT_SUCCESS';
export const DELETE_REQUESTS_COMMENT_FAILURE = 'DELETE_REQUESTS_COMMENT_FAILURE';


