export const GET_DOCUMENTLIST = 'GET_DOCUMENTLIST_REQUEST';
export const GET_DOCUMENTLIST_SUCCESS = 'GET_DOCUMENTLIST_SUCCESS';
export const GET_DOCUMENTLIST_FAILURE = 'GET_DOCUMENTLIST_FAILURE';

export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAILURE = 'UPLOAD_DOCUMENT_FAILURE';

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT_REQUEST';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_FAILURE = 'DELETE_DOCUMENT_FAILURE';


