export const GET_CATEGORY = "GET_CATEGORYS_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORYS_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORYS_FAILURE";

export const DELETE_CATEGORY = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const CREATE_CATEGORY = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const ACTIVATE_CATEGORY = "ACTIVATE_CATEGORY_REQUEST";
export const ACTIVATE_CATEGORY_SUCCESS = "ACTIVATE_CATEGORY_SUCCESS";
export const ACTIVATE_CATEGORY_FAILURE = "ACTIVATE_CATEGORY_FAILURE";

export const INACTIVATE_CATEGORY = "INACTIVATE_CATEGORY_REQUEST";
export const INACTIVATE_CATEGORY_SUCCESS = "INACTIVATE_CATEGORY_SUCCESS";
export const INACTIVATE_CATEGORY_FAILURE = "INACTIVATE_CATEGORY_FAILURE";

export const STRIPPED_CATEGORY = "STRIPPED_CATEGORY_REQUEST";
export const STRIPPED_CATEGORY_SUCCESS = "STRIPPED_CATEGORY_SUCCESS";
export const STRIPPED_CATEGORY_FAILURE = "STRIPPED_CATEGORY_FAILURE";

export const STRIPPED_CATEGORY_BY_NATURE = "STRIPPED_CATEGORY_BY_NATURE_REQUEST";
export const STRIPPED_CATEGORY_BY_NATURE_SUCCESS = "STRIPPED_CATEGORY_BY_NATURE_SUCCESS";
export const STRIPPED_CATEGORY_BY_NATURE_FAILURE = "STRIPPED_CATEGORY_BY_NATURE_FAILURE";
