export const GET_RESOURCE = 'RESOURCE_REQUEST';
export const RESOURCE_SUCCESS = 'RESOURCE_SUCCESS';
export const RESOURCE_FAILURE = 'RESOURCE_FAILURE';

export const GET_CATEGORIES_BY_NATURE = 'GET_CATEGORIES_BY_NATURE_REQUEST';
export const GET_CATEGORIES_BY_NATURE_SUCCESS = 'GET_CATEGORIES_BY_NATURE_SUCCESS';
export const GET_CATEGORIES_BY_NATURE_FAILURE = 'GET_CATEGORIES_BY_NATURE_FAILURE';

