export const GET_TRAINING_REPORT_BY_MODULE = 'GET_TRAINING_REPORT_BY_MODULE_REQUEST';
export const GET_TRAINING_REPORT_BY_MODULE_SUCCESS = 'GET_TRAINING_REPORT_BY_MODULE_SUCCESS';
export const GET_TRAINING_REPORT_BY_MODULE_FAILURE = 'GET_TRAINING_REPORT_BY_MODULE_FAILURE';

export const GET_TRAINING_REPORT_BY_RETAILER = 'GET_TRAINING_REPORT_BY_RETAILER_REQUEST';
export const GET_TRAINING_REPORT_BY_RETAILER_SUCCESS = 'GET_TRAINING_REPORT_BY_RETAILER_SUCCESS';
export const GET_TRAINING_REPORT_BY_RETAILER_FAILURE = 'GET_TRAINING_REPORT_BY_RETAILER_FAILURE';

export const GET_TRAINING_REPORT_BY_INCENTIVE = 'GET_TRAINING_REPORT_BY_INCENTIVE_REQUEST';
export const GET_TRAINING_REPORT_BY_INCENTIVE_SUCCESS = 'GET_TRAINING_REPORT_BY_INCENTIVE_SUCCESS';
export const GET_TRAINING_REPORT_BY_INCENTIVE_FAILURE = 'GET_TRAINING_REPORT_BY_INCENTIVE_FAILURE';

export const GET_RATIO_REPORT = 'GET_RATIO_REPORT_REQUEST';
export const GET_RATIO_REPORT_SUCCESS = 'GET_RATIO_REPORT_SUCCESS';
export const GET_RATIO_REPORT_FAILURE = 'GET_RATIO_REPORT_FAILURE';

export const GET_REQUESTS_REPORT = 'GET_REQUESTS_REPORT_REQUEST';
export const GET_REQUESTS_REPORT_SUCCESS = 'GET_REQUESTS_REPORT_SUCCESS';
export const GET_REQUESTS_REPORT_FAILURE = 'GET_REQUESTS_REPORT_FAILURE';

export const GET_TIME_RQUESTS_REPORT = 'GET_TIME_RQUESTS_REPORT_REQUEST';
export const GET_TIME_RQUESTS_REPORT_SUCCESS = 'GET_TIME_RQUESTS_REPORT_SUCCESS';
export const GET_TIME_RQUESTS_REPORT_FAILURE = 'GET_TIME_RQUESTS_REPORT_FAILURE';

export const GET_RETAILER_REPORT = 'GET_RETAILER_REPORT_REQUEST';
export const GET_RETAILER_REPORT_SUCCESS = 'GET_RETAILER_REPORT_SUCCESS';
export const GET_RETAILER_REPORT_FAILURE = 'GET_RETAILER_REPORT_FAILURE';

