export const GET_STRIPPED_RETAILER = "GET_STRIPPED_RETAILER_REQUEST";
export const GET_STRIPPED_RETAILER_SUCCESS = "GET_STRIPPED_RETAILER_SUCCESS";
export const GET_STRIPPED_RETAILER_FAILURE = "GET_STRIPPED_RETAILER_SUCCESS";

export const GET_RETAILER = "GET_RETAILER_REQUEST";
export const GET_RETAILER_SUCCESS = "GET_RETAILER_SUCCESS";
export const GET_RETAILER_FAILURE = "GET_RETAILER_SUCCESS";

export const GET_RETAILER_BY_ID = "GET_RETAILER_BY_ID_REQUEST";
export const GET_RETAILER_BY_ID_SUCCESS = "GET_RETAILER_BY_ID_SUCCESS";
export const GET_RETAILER_BY_ID_FAILURE = "GET_RETAILER_BY_ID_SUCCESS";

export const GET_RETAILER_AGENT = "GET_RETAILER_AGENT";
export const GET_RETAILER_AGENT_SUCCESS = "GET_RETAILER_AGENT_SUCCESS";
export const GET_RETAILER_AGENT_FAILURE = "GET_RETAILER_AGENT_FAILURE";

export const ASSIGN_AGENT_TO_RETAILER = "ASSIGN_AGENT_TO_RETAILER_REQUEST";
export const ASSIGN_AGENT_TO_RETAILER_SUCCESS = "ASSIGN_AGENT_TO_RETAILER_SUCCESS";
export const ASSIGN_AGENT_TO_RETAILER_FAILURE = "ASSIGN_AGENT_TO_RETAILER_FAILURE";

export const GET_FROM_FILE = "GET_FROM_FILE_REQUEST";
export const GET_FROM_FILE_SUCCESS = "GET_FROM_FILE_SUCCESS";
export const GET_FROM_FILE_FAILURE = "GET_FROM_FILE_SUCCESS";

export const ASSIGN_SALE_REPRESENTATIVE = "ASSIGN_SALE_REPRESENTATIVE_REQUEST";
export const ASSIGN_SALE_REPRESENTATIVE_SUCCESS = "ASSIGN_SALE_REPRESENTATIVE_SUCCESS";
export const ASSIGN_SALE_REPRESENTATIVE_FAILURE = "ASSIGN_SALE_REPRESENTATIVE_FAILURE";

export const GET_MUNCIPALITIES = "GET_MUNCIPALITIES_REQUEST";
export const GET_MUNCIPALITIES_SUCCESS = "GET_MUNCIPALITIES_SUCCESS";
export const GET_MUNCIPALITIES_FAILURE = "GET_MUNCIPALITIES_SUCCESS";

export const MASS_ASSIGNMENT = "MASS_ASSIGNMENT_REQUEST";
export const MASS_ASSIGNMENT_SUCCESS = "MASS_ASSIGNMENT_SUCCESS";
export const MASS_ASSIGNMENT_FAILURE = "MASS_ASSIGNMENT_FAILURE";