export const GET_NOTIFICATION = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAILURE = 'GET_NOTIFICATION_FAILURE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION_REQUEST';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';

export const GET_NOTIFICATION_BY_ID = 'GET_NOTIFICATION_BY_ID_REQUEST';
export const GET_NOTIFICATION_BY_ID_SUCCESS = 'GET_NOTIFICATION_BY_ID_SUCCESS';
export const GET_NOTIFICATION_BY_ID_FAILURE = 'GET_NOTIFICATION_BY_ID_FAILURE';

