export const GET_STRIPPED_MODULES = "GET_STRIPPED_MODULES_REQUEST";
export const GET_STRIPPED_MODULES_SUCCESS = "GET_STRIPPED_MODULES_SUCCESS";
export const GET_STRIPPED_MODULES_FAILURE = "GET_STRIPPED_MODULES_FAILURE";

export const GET_TRAINING_MODULE = "GET_TRAINING_MODULE_REQUEST";
export const GET_TRAINING_MODULE_SUCCESS = "GET_TRAINING_MODULE_SUCCESS";
export const GET_TRAINING_MODULE_FAILURE = "GET_TRAINING_MODULE_FAILURE";

export const CREATE_TRAINING_MODULE = "CREATE_TRAINING_MODULE_REQUEST";
export const CREATE_TRAINING_MODULE_SUCCESS = "CREATE_TRAINING_MODULE_SUCCESS";
export const CREATE_TRAINING_MODULE_FAILURE = "CREATE_TRAINING_MODULE_FAILURE";

export const DELETE_TRAINING_MODULE = "DELETE_TRAINING_MODULE_REQUEST";
export const DELETE_TRAINING_MODULE_SUCCESS = "DELETE_TRAINING_MODULE_SUCCESS";
export const DELETE_TRAINING_MODULE_FAILURE = "DELETE_TRAINING_MODULE_FAILURE";

export const GET_TRAINING_MODULE_BY_ID = "GET_TRAINING_MODULE_BY_ID_REQUEST";
export const GET_TRAINING_MODULE_BY_ID_SUCCESS = "GET_TRAINING_MODULE_BY_ID_SUCCESS";
export const GET_TRAINING_MODULE_BY_ID_FAILURE = "GET_TRAINING_MODULE_BY_ID_FAILURE";